server:
  port: 8000  # API Gateway runs on port 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: http://localhost:8001/
          predicates:
            - Path=/admin/**

        - id: doctor-service
          uri: http://localhost:8002/
          predicates:
            - Path=/doctor/**

        - id: patient-service
          uri: http://localhost:8003/
          predicates:
            - Path=/patient/**

        - id: query-service
          uri: http://localhost:8004/
          predicates:
            - Path=/query/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
