main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:    
  port: 8004
spring:
  application:
    name : QUERY-SERVICE